config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role?(:admin) } do
    mount PgHero::Engine, at: 'pghero'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  mount API => '/'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'discourse/sso' => 'discourse_sso#sso'

  authenticate :user, ->(user) { user.has_role?(:admin) } do
    namespace :admin do
      resources :invites
      resources :articles
      resources :categories
      resources :polls do
        resources :poll_answers
      end
      resources :clubs
      resources :users

      root to: 'invites#index'
    end
  end

  get '/klubbadmin/:id', to: 'admin/clubs#edit', as: :club_admin
  patch '/klubbadmin/:id', to: 'admin/clubs#update'

  # TODO: Break out into users_controller and profile_controller?
  get '/golfare', to: 'users#index', as: :users
  get '/golfare/:id', to: 'profile#show', as: :user
  get '/profil', to: 'profile#index', as: :profile
  get '/profil/vanner/', to: 'profile#friends', as: :friends
  get '/profil/rundor', to: 'profile#rounds', as: :user_rounds

  get '/profil/bild', to: 'profile#avatar', as: :profile_avatar
  get '/profil/omslagsbild', to: 'profile#coverimage', as: :profile_cover
  put '/profil/bild', to: 'profile#update_avatar', as: :update_avatar
  put '/profil/omslagsbild', to: 'profile#update_cover', as: :update_cover
  delete '/profil/bild', to: 'profile#delete_avatar', as: :delete_avatar
  delete '/profil/omslagsbild', to: 'profile#delete_cover', as: :delete_cover

  resources :rounds, path: 'rundor'
  resources :articles, only: %i[index show], path: 'artiklar'
  resources :posts, except: [:index], path: 'golfsnack' do
    resources :images, only: [:destroy]
    delete '/mainimage', to: 'images#mainimage', as: :destroy_mainimage
  end
  resources :comments, only: %i[create destroy], path: 'kommentarer'
  resources :clubs, only: %i[index show], path: 'golfklubbar' do
    collection { get 'search' }
    get '/bild', to: 'clubs#logo', as: :logo
    get '/omslagsbild', to: 'clubs#cover', as: :cover
    put '/bild', to: 'clubs#update_logo', as: :update_logo
    put '/omslagsbild', to: 'clubs#update_cover', as: :update_cover
    delete '/bild', to: 'clubs#delete_logo', as: :delete_logo
    delete '/omslagsbild', to: 'clubs#delete_cover', as: :delete_cover
  end

  post '/follow', to: 'follows#create', as: :follow
  post '/unfollow', to: 'follows#destroy', as: :unfollow
  post '/like', to: 'likes#create', as: :like
  post '/unlike', to: 'likes#destroy', as: :unlike

  post '/vote', to: 'polls#vote', as: :vote

  get '/ledartavla', to: 'leaderboard#index', as: :leaderboard
  get '/anvandaravtal', to: 'public#useragreement', as: :user_agreement
  get '/vanliga-fragor-och-svar', to: 'public#faq', as: :faq
  get '/shop', to: 'public#shop', as: :shop
  get '/om-golfsnack', to: 'public#about_us', as: :about_us

  root to: 'home#index'

  get '/styleguide', to: 'styleguide#index' if Rails.env.development?
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  belongs_to :category
  counter_culture :category

  has_one_attached :image
  has_rich_text :body
  friendly_id :title, use: :slugged

  validates :title, :image, :body, :category, presence: true

  def read_minutes
    body_in_database ? body_in_database.scan(/\w+/).size / 275 : 3
  end
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

module Admin
  class ArticlesController < BaseController
    def new
      @article = Article.new
    end

    def edit
      @article = Article.friendly.find(params[:id])
    end

    def index
      @articles = Article.all
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        flash[:success] = 'Artikel skapad'
        redirect_to admin_articles_path
      else
        flash.now[:error] = 'Något gick fel'
        render :new
      end
    end

    def update
      @article = Article.friendly.find(params[:id])
      if @article.update(article_params)
        flash[:success] = 'Artikel uppdaterad'
        redirect_to admin_articles_path
      else
        flash.now[:error] = 'Något gick fel'
        render :edit
      end
    end

    private

    def article_params
      params.require(:article).permit(:title, :image, :body, :preamble, :category_id)
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!
  layout 'application'

  def index
    @articles = Article.includes([:rich_text_body,
                                  { image_attachment: :blob }]).order(created_at: :desc).page params[:page]
    if params[:category]
      @category = Category.where(name: params[:category].capitalize).first
      @articles = @articles.where(category_id: @category.id) if @category
    else
      @latest_articles = (@articles + @articles + @articles).first(8)
    end
  end

  def show
    @article = Article.includes([:rich_text_body, { image_attachment: :blob }]).friendly.find(params[:id])
  end
end

app/views/admin/articles/_form.html.erb
<ul>
  <% @article.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<%= form_for [:admin, @article], html: { multipart: true } do |f| %>
  <label>Kategori</label>
  <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, placeholder: "Välj en kategori...", class: "w-full" %>
  <hr class="my-4" />
  <label>Rubrik</label>
  <%= f.text_field :title %>
  <div class="my-12">
    <%= image_tag @article.image if @article.image.attached? %>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <label>Inledning</label>
  <div class="mb-12">
    <%= f.text_area :preamble, rows: 7, class: "w-full" %>
  </div>
  <label>Innehåll</label>
  <div class="mb-12 control">
    <%= f.rich_text_area :body, rows: 20 %>
  </div>
  <div class="actions mt-12">
    <%= f.submit 'Spara artikel' %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h2 class="mb-6">Redigera Artikel</h2>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<div class="flex pb-12">
  <h2>Artiklar</h2>
  <%= link_to "Ny artikel", new_admin_article_path, class: "flex-0 ml-auto px-4 py-2 text-sm font-medium leading-5 text-sand-700 transition duration-150 ease-in-out bg-white border border-sand-300 hover:text-sand-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:text-sand-800 active:bg-sand-50"%>
</div>
<table class="w-full divide-y divide-sand-200">
  <thead>
    <tr>
      <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left uppercase text-sand-500 bg-sand-50">
        Titel
      </th>
      <th>
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-sand-200 text-xs">
    <% @articles.each do |article| %>
      <tr>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= article.title %>
        </td>
        <td>
          <%= article.category ? article.category.name : "Ingen kategori" %>
        </td>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= link_to "Redigera artikel", edit_admin_article_path(article) %>
          &nbsp;
          <%= link_to "Radera artikel", admin_article_path(article), method: :delete, data: { confirm: "Säker?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/articles/new.html.erb
<h2 class="mb-6">Ny Artikel</h2>
<%= render 'form' %>