config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role?(:admin) } do
    mount PgHero::Engine, at: 'pghero'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  mount API => '/'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'discourse/sso' => 'discourse_sso#sso'

  authenticate :user, ->(user) { user.has_role?(:admin) } do
    namespace :admin do
      resources :invites
      resources :articles
      resources :categories
      resources :polls do
        resources :poll_answers
      end
      resources :clubs
      resources :users

      root to: 'invites#index'
    end
  end

  get '/klubbadmin/:id', to: 'admin/clubs#edit', as: :club_admin
  patch '/klubbadmin/:id', to: 'admin/clubs#update'

  # TODO: Break out into users_controller and profile_controller?
  get '/golfare', to: 'users#index', as: :users
  get '/golfare/:id', to: 'profile#show', as: :user
  get '/profil', to: 'profile#index', as: :profile
  get '/profil/vanner/', to: 'profile#friends', as: :friends
  get '/profil/rundor', to: 'profile#rounds', as: :user_rounds

  get '/profil/bild', to: 'profile#avatar', as: :profile_avatar
  get '/profil/omslagsbild', to: 'profile#coverimage', as: :profile_cover
  put '/profil/bild', to: 'profile#update_avatar', as: :update_avatar
  put '/profil/omslagsbild', to: 'profile#update_cover', as: :update_cover
  delete '/profil/bild', to: 'profile#delete_avatar', as: :delete_avatar
  delete '/profil/omslagsbild', to: 'profile#delete_cover', as: :delete_cover

  resources :rounds, path: 'rundor'
  resources :articles, only: %i[index show], path: 'artiklar'
  resources :posts, except: [:index], path: 'golfsnack' do
    resources :images, only: [:destroy]
    delete '/mainimage', to: 'images#mainimage', as: :destroy_mainimage
  end
  resources :comments, only: %i[create destroy], path: 'kommentarer'
  resources :clubs, only: %i[index show], path: 'golfklubbar' do
    collection { get 'search' }
    get '/bild', to: 'clubs#logo', as: :logo
    get '/omslagsbild', to: 'clubs#cover', as: :cover
    put '/bild', to: 'clubs#update_logo', as: :update_logo
    put '/omslagsbild', to: 'clubs#update_cover', as: :update_cover
    delete '/bild', to: 'clubs#delete_logo', as: :delete_logo
    delete '/omslagsbild', to: 'clubs#delete_cover', as: :delete_cover
  end

  post '/follow', to: 'follows#create', as: :follow
  post '/unfollow', to: 'follows#destroy', as: :unfollow
  post '/like', to: 'likes#create', as: :like
  post '/unlike', to: 'likes#destroy', as: :unlike

  post '/vote', to: 'polls#vote', as: :vote

  get '/ledartavla', to: 'leaderboard#index', as: :leaderboard
  get '/anvandaravtal', to: 'public#useragreement', as: :user_agreement
  get '/vanliga-fragor-och-svar', to: 'public#faq', as: :faq
  get '/shop', to: 'public#shop', as: :shop
  get '/om-golfsnack', to: 'public#about_us', as: :about_us

  root to: 'home#index'

  get '/styleguide', to: 'styleguide#index' if Rails.env.development?
end

app/models/poll.rb
# frozen_string_literal: true

class Poll < ApplicationRecord
  has_many :poll_questions, dependent: :destroy
  has_many :poll_answers, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :poll_questions, presence: true, length: { minimum: 2 }

  accepts_nested_attributes_for :poll_questions, allow_destroy: true

  scope :active, -> { where.not(archived: true) }
end

app/controllers/admin/polls_controller.rb
# frozen_string_literal: true

module Admin
  class PollsController < BaseController
    def new
      @poll = Poll.new
      10.times do |_i|
        @poll.poll_questions.build
      end
    end

    def edit
      @poll = Poll.find(params[:id])
      (10 - @poll.poll_questions_count).times do
        @poll.poll_questions.build
      end
    end

    def index
      @polls = Poll.all
    end

    def create
      @poll = Poll.new(param_clean(poll_params))
      if @poll.save
        flash[:success] = 'Omröstning skapad'
        redirect_to admin_polls_path
      else
        flash.now[:error] = 'Något gick fel'
        render :new
      end
    end

    def update
      @poll = Poll.find(params[:id])
      if @poll.update(param_clean(poll_params))
        flash[:success] = 'Omröstning uppdaterad'
        redirect_to admin_polls_path
      else
        flash.now[:error] = 'Något gick fel'
        render :edit
      end
    end

    private

    def poll_params
      params.require(:poll).permit(:name, :archived, poll_questions_attributes: %i[id choice _destroy])
    end

    def param_clean(params_to_clean)
      params_to_clean.delete_if do |_k, v|
        param_clean(v) if v.instance_of?(ActionController::Parameters)
        v.empty?
      end
    end
  end
end

app/controllers/polls_controller.rb
# frozen_string_literal: true

class PollsController < ApplicationController
  before_action :authenticate_user!

  def vote
    if poll_params[:poll_question_id]
      answer = PollAnswer.new(poll_params)
      answer.user = current_user
      answer.save!
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def poll_params
    params.require(:poll_answer).permit(:poll_id, :poll_question_id)
  end
end

app/views/admin/polls/_form.html.erb
<ul>
  <% @poll.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<%= form_for [:admin, @poll], html: { multipart: true } do |f| %>
  <div class="my-12">
    <label class="font-bold">Rubrik</label>
    <%= f.text_field :name%>
    <div class="p-12 my-12 border-t border-golfsnack-500">
      <label class="font-bold">Val</label>
      <%= f.fields_for :poll_questions do |builder| %>
        <div class="pb-4">
          <%= builder.hidden_field :id %>
          <%= builder.text_field :choice %>
          <% if builder.object.persisted? %>
            <label class="text-xs">
              <%= builder.check_box :_destroy %> Radera val (OBS, Om ngn svarat på detta val tas detta svar bort!)
            </label>
          <% end %>
        </div>
      <% end %>
    </div>
    <label class="py-4 my-8">
      <%= f.check_box :archived  %> Arkivera omröstning (Går ej att svara på mer)
    </label>
  </div>
  <div class="actions">
    <%= f.submit 'Spara omröstning' %>
  </div>
<% end %>

app/views/admin/polls/edit.html.erb
<h2 class="mb-6">Redigera omröstning</h2>
<%= render 'form' %>

app/views/admin/polls/index.html.erb
<div class="flex pb-12">
  <h2>Omröstningar</h2>
  <%= link_to "Ny omröstning", new_admin_poll_path, class: "flex-0 ml-auto px-4 py-2 text-sm font-medium leading-5 text-sand-700 transition duration-150 ease-in-out bg-white border border-sand-300 hover:text-sand-500 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 active:text-sand-800 active:bg-sand-50"%>
</div>
<table class="min-w-full divide-y divide-sand-200">
  <thead>
    <tr>
      <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left uppercase text-sand-500 bg-sand-50">
        Titel
      </th>
      <th>
        Status
      </th>
      <th>
      </th>
      <th>
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-sand-200 text-xs">
    <% @polls.each do |poll| %>
      <tr>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= poll.name %>
        </td>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= poll.archived? ? "Arkiverad" : "Aktiv" %>
        </td>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= link_to "Se svar", admin_poll_poll_answers_path(poll) %>
        </td>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= link_to "Redigera omröstning", edit_admin_poll_path(poll) %>
        </td>
        <td class="px-6 py-4 whitespace-no-wrap">
          <%= link_to "Radera omröstning", admin_poll_path(poll), method: :delete, data: { confirm: "Säker?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/polls/new.html.erb
<h2 class="mb-6">Ny omröstning</h2>
<%= render 'form' %>