config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role?(:admin) } do
    mount PgHero::Engine, at: 'pghero'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  mount API => '/'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'discourse/sso' => 'discourse_sso#sso'

  authenticate :user, ->(user) { user.has_role?(:admin) } do
    namespace :admin do
      resources :invites
      resources :articles
      resources :categories
      resources :polls do
        resources :poll_answers
      end
      resources :clubs
      resources :users

      root to: 'invites#index'
    end
  end

  get '/klubbadmin/:id', to: 'admin/clubs#edit', as: :club_admin
  patch '/klubbadmin/:id', to: 'admin/clubs#update'

  # TODO: Break out into users_controller and profile_controller?
  get '/golfare', to: 'users#index', as: :users
  get '/golfare/:id', to: 'profile#show', as: :user
  get '/profil', to: 'profile#index', as: :profile
  get '/profil/vanner/', to: 'profile#friends', as: :friends
  get '/profil/rundor', to: 'profile#rounds', as: :user_rounds

  get '/profil/bild', to: 'profile#avatar', as: :profile_avatar
  get '/profil/omslagsbild', to: 'profile#coverimage', as: :profile_cover
  put '/profil/bild', to: 'profile#update_avatar', as: :update_avatar
  put '/profil/omslagsbild', to: 'profile#update_cover', as: :update_cover
  delete '/profil/bild', to: 'profile#delete_avatar', as: :delete_avatar
  delete '/profil/omslagsbild', to: 'profile#delete_cover', as: :delete_cover

  resources :rounds, path: 'rundor'
  resources :articles, only: %i[index show], path: 'artiklar'
  resources :posts, except: [:index], path: 'golfsnack' do
    resources :images, only: [:destroy]
    delete '/mainimage', to: 'images#mainimage', as: :destroy_mainimage
  end
  resources :comments, only: %i[create destroy], path: 'kommentarer'
  resources :clubs, only: %i[index show], path: 'golfklubbar' do
    collection { get 'search' }
    get '/bild', to: 'clubs#logo', as: :logo
    get '/omslagsbild', to: 'clubs#cover', as: :cover
    put '/bild', to: 'clubs#update_logo', as: :update_logo
    put '/omslagsbild', to: 'clubs#update_cover', as: :update_cover
    delete '/bild', to: 'clubs#delete_logo', as: :delete_logo
    delete '/omslagsbild', to: 'clubs#delete_cover', as: :delete_cover
  end

  post '/follow', to: 'follows#create', as: :follow
  post '/unfollow', to: 'follows#destroy', as: :unfollow
  post '/like', to: 'likes#create', as: :like
  post '/unlike', to: 'likes#destroy', as: :unlike

  post '/vote', to: 'polls#vote', as: :vote

  get '/ledartavla', to: 'leaderboard#index', as: :leaderboard
  get '/anvandaravtal', to: 'public#useragreement', as: :user_agreement
  get '/vanliga-fragor-och-svar', to: 'public#faq', as: :faq
  get '/shop', to: 'public#shop', as: :shop
  get '/om-golfsnack', to: 'public#about_us', as: :about_us

  root to: 'home#index'

  get '/styleguide', to: 'styleguide#index' if Rails.env.development?
end

app/views/shared/_actions.html.erb
<% if user_signed_in? %>
  <div class="actions">
    <div class="row">
      <div class="col-xs-6 like">
        <%= render 'likes/form', likeable: resource %>
      </div>
      <div class="col-xs-6 comment">
        <%= link_to resource, class: 'btn btn-block' do %>
          Kommentera
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_activity.html.erb
<%= render_activity(activity) %>

app/views/shared/_article.html.erb
<div class="w-1/3 p-4 bg-white">
  <%= image_tag article.image, class: "w-full" %>
  <%= link_to article.title, article_path(article), class: "block text-xl font-semibold leading-7"%>
  <p class="mt-3 text-base leading-6"><%= truncate(strip_tags(article.body.to_s), length: 300) %></p>
  <%= link_to "Läs artikeln » (#{article.read_minutes} min)", article_path(article), class: "leading-7" %>
</div>

app/views/shared/_avatar.html.erb
<% if user %>
  <%= link_to user, "data-turbo-frame": "_top" do %>
    <% if user.avatar.attached? %>
      <%= image_tag user.avatar, class: 'small-avatar' %>
    <% else %>
      <%= image_tag "fallback/avatar-thumb-default.png", class: 'small-avatar' %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_avatar_group.html.erb
<div class="flex justify-center">
  <% users.each_with_index do |user, index| %>
    <%= link_to user_path(user), class: "flex justify-center items-center mr-1" do %>
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar, class: "mini-avatar" %>
      <% else %>
        <%= image_tag "fallback/avatar-thumb-default.png", class: "mini-avatar" %>
      <% end %>
    <% end %>
  <% end %>
  <% if extra %>
    <span class="flex items-center justify-center font-semibold text-xs text-golfsnack-200 w-8 h-8 bg-wetsand-700 mini-avatar">+<%=extra%></span>
  <% end %>
</div>

app/views/shared/_clap.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 126 132" fill="#fff" fill-rule="evenodd" stroke="#000" stroke-linecap="round" stroke-linejoin="round">
  <use xlink:href="#a" x="2" y="2"/>
  <symbol id="a" overflow="visible">
    <g fill="#E3BE00" fill-rule="nonzero">
      <path d="M104 82l-3-16-4-30c-5-4-11 4-12 10L79 9c-1-8-15-6-14 3l5 29-6-35c-1-8-14-9-12 5-1-7-15-7-13 4l1 12 1 1-1-3c-1-7-13-5-11 3l2 14" stroke="#fcea2b" stroke-width="4.2" stroke-miterlimit="10"/>
      <use xlink:href="#C" stroke="none"/>
    </g>
    <g stroke-width="4.2" fill="none">
      <use xlink:href="#C"/>
      <path d="M49 81L21 53m36 17L29 42M14 82c-6-6 2-15 7-10l20 21M14 65c-8-8 3-16 8-11m7-12c-5-5-17 2-7 12m74 16L74 47c-6 0-7 10-5 16l8 7-34-34c-6-5-16 4-9 11M14 65l10 10m72-5a33 33 0 01-46 47M14 82l36 36m6-79l-4-29M70 41L64 6M29 28c-2-8 10-10 11-3l1 3m-2-13C37 4 51 4 52 11"/>
      <path d="M64 6c-1-8-14-9-12 5m50 55c-2-6-2-15-4-30-6-3-12 4-13 10L79 9c-1-8-15-6-14 3m-26 3l1 12m-11 1v4M18 17L16 4m-4 24L0 34m15-12L5 17m95 3L99 7m10 23l13 2m-17-8l8-6"/>
    </g>
  </symbol>
  <defs>
    <path id="C" d="M34 47c-7-7 3-16 9-11l26 27c-2-6-1-16 5-16l22 23a33 33 0 01-46 47L14 82c-6-6 2-15 7-10l3 3-10-10c-8-8 3-16 8-11-10-10 2-17 7-12l28 28"/>
  </defs>
</svg>

app/views/shared/_comment.html.erb
<div class="flex flex-row pt-4 pl-6 mt-4 border-t border-golfsnack-100">
  <%= render 'shared/avatar', user: comment.user  %>
  <div class="flex-col mt-1">
    <div class="flex flex-1 px-4 text-sm font-bold leading-tigh">
      <%= link_to comment.user.name, user_path(comment.user) %>
      <span class="self-end ml-2 text-xs font-normal text-golfsnack-500"><%= relative_time comment.created_at %> sedan</span>
    </div>
    <div class="flex-1 ml-4 text-sm font-medium leading-loose text-golfsnack-600">
      <%= comment.comment %>
    </div>
  </div>
</div>

app/views/shared/_created_at.html.erb
För <%= relative_time(activity.created_at) %> sedan

app/views/shared/_noclap.html.erb
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 126 132" fill="#fff" fill-rule="evenodd" stroke="#000" stroke-linecap="round" stroke-linejoin="round">
  <use xlink:href="#b" x="2" y="2"/>
  <symbol id="b" overflow="visible">
    <g fill="#FFF" fill-rule="nonzero">
      <path d="M104 82l-3-16-4-30c-5-4-11 4-12 10L79 9c-1-8-15-6-14 3l5 29-6-35c-1-8-14-9-12 5-1-7-15-7-13 4l1 12 1 1-1-3c-1-7-13-5-11 3l2 14" stroke="#fcea2b" stroke-width="4.2" stroke-miterlimit="10"/>
      <use xlink:href="#D" stroke="none"/>
    </g>
    <g stroke-width="4.2" fill="none">
      <use xlink:href="#D"/>
      <path d="M49 81L21 53m36 17L29 42M14 82c-6-6 2-15 7-10l20 21M14 65c-8-8 3-16 8-11m7-12c-5-5-17 2-7 12m74 16L74 47c-6 0-7 10-5 16l8 7-34-34c-6-5-16 4-9 11M14 65l10 10m72-5a33 33 0 01-46 47M14 82l36 36m6-79l-4-29M70 41L64 6M29 28c-2-8 10-10 11-3l1 3m-2-13C37 4 51 4 52 11"/>
      <path d="M64 6c-1-8-14-9-12 5m50 55c-2-6-2-15-4-30-6-3-12 4-13 10L79 9c-1-8-15-6-14 3m-26 3l1 12m-11 1v4M18 17L16 4m-4 24L0 34m15-12L5 17m95 3L99 7m10 23l13 2m-17-8l8-6"/>
    </g>
  </symbol>
  <defs>
    <path id="D" d="M34 47c-7-7 3-16 9-11l26 27c-2-6-1-16 5-16l22 23a33 33 0 01-46 47L14 82c-6-6 2-15 7-10l3 3-10-10c-8-8 3-16 8-11-10-10 2-17 7-12l28 28"/>
  </defs>
</svg>

app/views/shared/_reactions.html.erb
<% if current_user && !is_current_user?(item.user) %>
  <turbo-frame id="<%= item.class.to_s%>-<%=item.id%>-reactions">
    <% if current_user.liked? item %>
      <%= button_to unlike_path(likeable_type: item.class.to_s, likeable_id: item.id), method: :post do %>
        <span class="<%= local_assigns.fetch :animate, "no-animate"%>">
          <%= render partial: 'shared/clap' %>
        </span>
        <span><%= pluralize(item.get_likes.size, "golfklapp", locale: :sv) %></span>
      <% end %>
    <% else %>
      <%= button_to like_path(likeable_type: item.class.to_s, likeable_id: item.id), method: :post do %>
        <span class="<%= local_assigns.fetch :animate, "no-animate"%>">
          <%= render partial: 'shared/noclap' %>
        </span>
        <span><%= pluralize(item.get_likes.size, "golfklapp", locale: :sv) %></span>
      <% end %>
    <% end %>
  </turbo-frame>
<% else %>
  <div class="flex px-4 py-2">
    <%= render partial: 'shared/noclap' %>
    <span><%= pluralize(item.get_likes.size, "golfklapp", locale: :sv) %></span>
  </div>
<% end %>

app/views/shared/_tags.html.erb
<div class="flex flex-row min-w-full py-2 justify-start flex-wrap gap-1">
  <% tags.each do |tag| %>
    <a href="/?tag=<%=tag.name%>" class="tag" data-turbo-frame="_top">
      #<%= tag.name %>
    </a>
  <% end %>
</div>