config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(user) { user.has_role?(:admin) } do
    mount PgHero::Engine, at: 'pghero'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  mount API => '/'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'discourse/sso' => 'discourse_sso#sso'

  authenticate :user, ->(user) { user.has_role?(:admin) } do
    namespace :admin do
      resources :invites
      resources :articles
      resources :categories
      resources :polls do
        resources :poll_answers
      end
      resources :clubs
      resources :users

      root to: 'invites#index'
    end
  end

  get '/klubbadmin/:id', to: 'admin/clubs#edit', as: :club_admin
  patch '/klubbadmin/:id', to: 'admin/clubs#update'

  # TODO: Break out into users_controller and profile_controller?
  get '/golfare', to: 'users#index', as: :users
  get '/golfare/:id', to: 'profile#show', as: :user
  get '/profil', to: 'profile#index', as: :profile
  get '/profil/vanner/', to: 'profile#friends', as: :friends
  get '/profil/rundor', to: 'profile#rounds', as: :user_rounds

  get '/profil/bild', to: 'profile#avatar', as: :profile_avatar
  get '/profil/omslagsbild', to: 'profile#coverimage', as: :profile_cover
  put '/profil/bild', to: 'profile#update_avatar', as: :update_avatar
  put '/profil/omslagsbild', to: 'profile#update_cover', as: :update_cover
  delete '/profil/bild', to: 'profile#delete_avatar', as: :delete_avatar
  delete '/profil/omslagsbild', to: 'profile#delete_cover', as: :delete_cover

  resources :rounds, path: 'rundor'
  resources :articles, only: %i[index show], path: 'artiklar'
  resources :posts, except: [:index], path: 'golfsnack' do
    resources :images, only: [:destroy]
    delete '/mainimage', to: 'images#mainimage', as: :destroy_mainimage
  end
  resources :comments, only: %i[create destroy], path: 'kommentarer'
  resources :clubs, only: %i[index show], path: 'golfklubbar' do
    collection { get 'search' }
    get '/bild', to: 'clubs#logo', as: :logo
    get '/omslagsbild', to: 'clubs#cover', as: :cover
    put '/bild', to: 'clubs#update_logo', as: :update_logo
    put '/omslagsbild', to: 'clubs#update_cover', as: :update_cover
    delete '/bild', to: 'clubs#delete_logo', as: :delete_logo
    delete '/omslagsbild', to: 'clubs#delete_cover', as: :delete_cover
  end

  post '/follow', to: 'follows#create', as: :follow
  post '/unfollow', to: 'follows#destroy', as: :unfollow
  post '/like', to: 'likes#create', as: :like
  post '/unlike', to: 'likes#destroy', as: :unlike

  post '/vote', to: 'polls#vote', as: :vote

  get '/ledartavla', to: 'leaderboard#index', as: :leaderboard
  get '/anvandaravtal', to: 'public#useragreement', as: :user_agreement
  get '/vanliga-fragor-och-svar', to: 'public#faq', as: :faq
  get '/shop', to: 'public#shop', as: :shop
  get '/om-golfsnack', to: 'public#about_us', as: :about_us

  root to: 'home#index'

  get '/styleguide', to: 'styleguide#index' if Rails.env.development?
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @home = 'home'
    @article = Article.order('created_at desc').first

    # following_ids = current_user.following_users.map(&:id)
    # Post.where(user_id: following_ids).order("created_at DESC").paginate(page: params[:page])

    if params[:tag]
      @tag = params[:tag]
      @posts = Post.tagged_with(params[:tag])
                   .includes(user: [avatar_attachment: :blob])
                   .includes([:club])
                   .order('created_at desc')
                   .page(params[:page]).per(50)
    else
      @posts = Post.includes(user: [avatar_attachment: :blob])
                   .includes([:club])
                   .order('created_at desc')
                   .page(params[:page]).per(50)
    end
    @user = current_user

    top_scores = Merit::Score.top_scored(since: Date.yesterday)
    users = User.includes([:sash]).find(top_scores.map { |s| s['user_id'] })

    items = top_scores.map do |ts|
      user = users.find { |u| u.id.to_s == ts['user_id'].to_s }
      avatar = user.avatar.attached? ? Rails.application.routes.url_helpers.rails_blob_url(user.avatar, Rails.application.config.action_mailer.default_url_options) : ""
      LeaderboardItem.new(id: user.id, position: 0, name: user.name, avatar: avatar, sum_points: ts['sum_points'])
    end

    @leaderboard_users = StandardCompetitionRanking.new(items, rank_by: :sum_points, sort_direction: :desc).calculate

    @polls = Poll.active.order(:created_at).limit(3).all
    @popular_tags = ActsAsTaggableOn::Tag.most_used(10)
  end
end

app/views/home/_articles.html.erb
<section class="w-full mt-6 mb-12 carousel bg-golfsnack-100 px-4 py-1 rounded" aria-label="Gallery">
  <div class="grid py-6 md:grid-cols-3">
    <a href="<%= url_for @article %>" class="no-underline hover:underline hover:opacity-90">
      <%= image_tag @article.image, class: "object-cover w-full border-4 border-golfsnack-100" %>
    </a>
    <div class="w-full px-8 md:col-span-2">
      <a href="<%= url_for @article %>" class="block mb-4 no-underline hover:underline">
        <h2 class="mb-0 text-2xl font-extrabold leading-snug uppercase text-golfsnack-800">
          <%= @article.title%>
        </h2>
      </a>
      <%= @article.preamble %>
    </div>
  </div>
</section>

app/views/home/_blogs.html.erb
<div class="flex pb-4 pr-4 mb-4 border-b border-golfsnack-100">
  <h4 class="flex-1">INLÄGG</h4>
  <a href="#" class="flex mr-4 text-sm">ALLT</a>
  <a href="#" class="flex mr-4 text-sm">SCOREKORT</a>
  <a href="#" class="flex mr-4 text-sm">BANBETYG</a>
  <a href="#" class="flex text-sm">BILDER</a>
</div>
<div class="stories">
  <% @posts.each do |post| %>
    <article class="story" x-data="{ commentsOpen: false}">
      <div role="presentation">
        <div class="story__top">
          <div class="story__avatar">
            <%= render 'shared/avatar', user: post.user %>
          </div>
          <div class="story__meta">
            <div>
              <%= link_to post.user.name, post.user %>
              <% if post.club.present? %>
                @ <%= link_to post.club.name, post.club %>
              <% end %>
            </div>
            <%= render 'shared/created_at', activity: post %>
          </div>
        </div>
        <div class="story__body">
          <%= link_to post_path(post) do %>
            <% if post.title %>
              <h3><%= post.title%></h3>
            <% end %>
            <div class="story__body__body">
              <%= post.body %>
            </div>
          <% end %>
        </div>
        <div class="story__footer">
          <div class="story__reaction">
            <% if current_user.liked? post %>
              <%= form_tag unlike_path(likeable_type: post.class.to_s, likeable_id: post.id), method: :post do %>
                <% button_tag  do %>
                  <%= render partial: 'shared/clap' %>
                  <span><%= pluralize(post.get_likes.size, "golfklapp", locale: :sv) %></span>
                <% end %>
              <% end %>
            <% else %>
              <%= form_tag like_path(likeable_type: post.class.to_s, likeable_id: post.id) do %>
                <% button_tag do %>
                  <%= render partial: 'shared/noclap' %>
                  <span><%= pluralize(post.get_likes.size, "golfklapp", locale: :sv) %></span>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="story__reaction">
            <button @click="commentsOpen = !commentsOpen">
              <svg viewBox="0 0 95 78" xmlns="http://www.w3.org/2000/svg">
                <path d="M29.58 0c1.53.064 2.88 1.47 2.879 3v11.31c19.841.769 34.384 8.902 41.247 20.464 7.212 12.15 5.505 27.83-6.384 40.273-.987 1.088-2.82 1.274-4.005.405-1.186-.868-1.559-2.67-.814-3.936 4.986-9.075 2.985-18.092-3.13-24.214-5.775-5.78-15.377-8.782-26.914-5.53V53.99c-.01 1.167-.769 2.294-1.848 2.744-1.08.45-2.416.195-3.253-.62L.85 30.119c-1.146-1.124-1.131-3.205.032-4.312L27.389.812c.703-.579 1.49-.703 2.19-.812zm-3.13 9.935L7.297 27.994l19.153 18.84v-7.342c-.002-1.244.856-2.442 2.034-2.844 14.307-4.882 27.323-1.394 35.145 6.437 3.985 3.989 6.581 9.143 7.355 14.715 2.14-6.959 1.157-13.902-2.441-19.964-5.89-9.92-19.251-17.684-39.089-17.684-1.573 0-3.004-1.429-3.004-3V9.936z" fill-rule="nonzero" />
              </svg>
              <span><%= pluralize(post.comments.size, "kommentar", locale: :sv) %></span>
            </button>
          </div>
        </div>
        <div class="w-full comments" :class="{'block': commentsOpen, 'hidden': !commentsOpen }">
          <% post.comments.each do |comment| %>
            <%= render 'shared/comment', comment: comment %>
          <% end %>
          <%= render 'comments/form', commentable: post %>
        </div>
      </div>
    </article>
  <% end %>
</div>

app/views/home/_leaderboard.html.erb
<div class="p-4 mb-6 rounded bg-sand-100 shadow">
  <h3 class="w-full font-bold tracking-tighter text-center">GOLFSNACKS LEDARTAVLA</h2>
  <h5 class="w-full pb-4 mb-4 font-bold tracking-tighter text-center">V.<%= Date.today.strftime("%U").to_i %></h5>
  <table class="w-full divide-y divide-sand-200">
    <tbody class="w-full text-xs font-bold divide-y divide-wetsand-600 text-wetsand-800">
      <% @leaderboard_users.each do |user| %>
        <tr>
          <td class="py-2 pr-2 whitespace-no-wrap border-r border-wetsand-300">
            <%= user.position %>
          </td>
          <td class="pl-2 uppercase border-r border-wetsand-3 00">
            <%= link_to user.name, user_path(user.id) %>
          </td>
          <td class="pl-2 whitespace-no-wrap">
            <%= user.sum_points %>
          </td>
        </tr>
      <% end %>

    </tbody>
  </table>
  <%= link_to "Se hela listan",leaderboard_path, class: "w-full text-center mt-8 block text-sm no-underline hover:underline" %>
</div>

app/views/home/_polls.html.erb
<% @polls.each do |poll| %>
  <div class="relative p-4 bg-white rounded shadow">
    <%=turbo_frame_tag dom_id(poll) do %>
      <h3 class="absolute left-0 block arrow-title top-2">OMRÖSTNING</h3>
      <h4 class="block w-full px-4 py-4 mt-12 text-lg text-center uppercase border-t border-b border-wetsand-300 text-golfsnack-500"><%=poll.name%></h4>
      <% if poll.poll_answers.where(user_id: current_user.id).size > 0 %>
        <ul class="poll">
          <% poll.poll_questions.each do |question| %>
            <%- percentage = question.poll_answers.size > 0 ? ((question.poll_answers.size.to_f  / poll.poll_answers.size.to_f) * 100).round : 0 %>
            <style>
              .progress_<%= question.id %>:before {
                content: "";
                position: absolute;
                width: <%= percentage%>%;
                top: 0; left: 0; bottom: 0;
                height: 100%;
                background: #feb;
                z-index: 0;
              }
            </style>
            <li class="relative progress_<%= question.id %>">
              <label class="relative z-20 flex justify-between w-full px-4 text-xs ex">
                <%= question.choice %>
                <span class="text-xs">
                  <%= percentage %> %
                </span>
              </label>
            </li>
          <% end %>
        </ul>
        <div class="w-full py-2 mt-6 mb-8 text-center border-t border-b border-wetsand-300 text-wetsand-400">
          <h4><%= pluralize(poll.poll_answers.size, "RÖST", locale: :sv).upcase %></h4>
        </div>
      <% else %>
        <%= form_for(poll.poll_answers.new, url: vote_path) do |f| %>
          <%= f.hidden_field :poll_id %>
          <ul class="poll">
            <% poll.poll_questions.each do |question| %>
              <li class="px-4">
                <label class="text-xs">
                  <input type="radio" name="poll_answer[poll_question_id]" value="<%=question.id%>">
                  <%= question.choice %>
                </label>
              </li>
            <% end %>
          </ul>
          <%= f.submit "RÖSTA" , class: "block w-full btn" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/home/_popular_tags.html.erb
<div class="p-6 mt-6 rounded bg-golfsnack-100">
  <h4>Populära taggar</h4>
  <%= render 'shared/tags', tags: tags %>
</div>

app/views/home/_posts.html.erb
<div class="stories" data-controller="modal">
  <div class="w-full pb-4 mb-8 text-center border-b border-wetsand-300 text-golfsnack-500 flex">
    <h3>GOLFSNACK</h3>
    <% if @tag %>
      Visar golfsnack taggade med: <span class="font-bold text-golfsnack-400">#<%= @tag%></span>. <a href="/">Visa alla</a>
    <% end %>
    <% if @user && current_user == @user %>
      <%= link_to "Nytt golfsnack", "#", class: "ml-auto btn", "data-action": "click->modal#open" %>
    <% end %>
  </div>
  <% @posts.each do |post| %>
    <article id="post_<%=post.id%>" class="story rounded-2xl shadow-2xl">
      <div role="presentation">

        <div class="story__top">
          <div class="story__avatar">
            <%= render 'shared/avatar', user: post.user %>
          </div>
          <div class="story__meta">
            <div>
              <%= link_to post.user.name, post.user, "data-turbo-frame": "_top" %>
              <% if post.club.present? %>
                @ <%= link_to post.club.name, post.club, "data-turbo-frame": "_top" %>
              <% end %>
            </div>
            <%= render 'shared/tags', tags: post.tags %>
          </div>
          <div class="ml-auto story__meta">
            <%= render 'shared/created_at', activity: post %>
          </div>
        </div>
        <div class="story__body">
          <%= link_to post_path(post), "data-turbo-frame": "post-show" do %>
            <h4 class="font-semibold mb-2 text-golfsnack-600"><%= post.title %></h4>
            <% if post.youtube_url.present? %>
              <iframe width="100%" height="400" src="https://www.youtube.com/embed/<%= post.youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <% elsif post.mainimage.attached? %>
              <%= image_tag post.mainimage, class: "object-cover w-full mb-4" %>
            <% end %>
          <% end %>
            <div class="story__body__body">
              <%= simple_format(post.body.to_plain_text.truncate(400)) %>
            </div>
        </div>
        <div class="story__footer">
          <div class="story__reaction">
            <%= render 'shared/reactions', item: post %>
          </div>
          <div class="story__reaction">
            <%= link_to post_path(post), class: "btn", "data-turbo-frame": "post-show" do %>
              <svg viewBox="0 0 95 78" xmlns="http://www.w3.org/2000/svg">
                <path d="M29.58 0c1.53.064 2.88 1.47 2.879 3v11.31c19.841.769 34.384 8.902 41.247 20.464 7.212 12.15 5.505 27.83-6.384 40.273-.987 1.088-2.82 1.274-4.005.405-1.186-.868-1.559-2.67-.814-3.936 4.986-9.075 2.985-18.092-3.13-24.214-5.775-5.78-15.377-8.782-26.914-5.53V53.99c-.01 1.167-.769 2.294-1.848 2.744-1.08.45-2.416.195-3.253-.62L.85 30.119c-1.146-1.124-1.131-3.205.032-4.312L27.389.812c.703-.579 1.49-.703 2.19-.812zm-3.13 9.935L7.297 27.994l19.153 18.84v-7.342c-.002-1.244.856-2.442 2.034-2.844 14.307-4.882 27.323-1.394 35.145 6.437 3.985 3.989 6.581 9.143 7.355 14.715 2.14-6.959 1.157-13.902-2.441-19.964-5.89-9.92-19.251-17.684-39.089-17.684-1.573 0-3.004-1.429-3.004-3V9.936z" fill-rule="nonzero" />
              </svg>
              <span><%= pluralize(post.comments_count, "kommentar", locale: :sv) %></span>
            <% end %>
          </div>
        </div>
      </div>
    </article>
  <% end %>
  <% if @user && current_user == @user %>
    <div id="new-post-modal" data-modal-target="container" data-action="click->modal#closeBackground keyup@window->modal#closeWithKeyboard" class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center w-90 h-90" style="z-index: 9999;">
      <div class="modal-container bg-white mx-auto rounded shadow-lg z-50 overflow-y-auto p-12 relative max-w-screen-xl m-12 h-4/6">
        <button data-action="click->modal#close" class="absolute top-2 right-2">
          <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
          </svg>
        </button>
        <%= turbo_frame_tag "post_form", src: new_post_path, target: "_top" %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/_user_sidebar.html.erb
<div class="p-4 bg-white rounded shadow">
  <div class="flex items-center justify-center">
    <%= link_to user do %>
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar, class: 'avatar' %>
      <% else %>
        <%= image_tag "fallback/avatar-thumb-default.png", class: 'avatar' %>
      <% end %>
    <% end %>
  </div>
  <div class="flex flex-col items-center justify-center">
    <%= link_to user do %>
      <h3 class="mt-4 uppercase text-wetsand-800"><%= user.first_name %> <%= user.last_name %></h3>
    <% end %>
    <% if user.club %>
      <%= link_to user.club do %>
        <h4 class="mt-2 font-normal uppercase text-fairway-600"><%= user.club.name %></h4>
      <% end %>
    <% end %>
    <div class="grid grid-cols-3 w-full my-6 divide-x divide-golfsnack-500">
      <div class="flex flex-col gap-2 w-full">
        <span class="w-full text-center text-sm text-gray-500 uppercase">Följare</span>
        <%= link_to friends_path do %>
          <h5 class="w-full text-xl text-center text-gray-700"><%= user.user_followers.size %></h5>
        <% end %>
      </div>
      <div class="flex flex-col gap-2 w-full">
        <span class="w-full text-center text-sm text-gray-500 uppercase">Följer</span>
        <%= link_to friends_path do %>
          <h5 class="w-full text-xl text-center text-gray-700"><%= user.following_users.size %></h5>
        <% end %>
      </div>
      <div class="flex flex-col gap-2 w-full">
        <span class="w-full text-center text-sm text-gray-500 uppercase">Rundor</span>
        <%= link_to user_rounds_path do %>
          <h5 class="w-full text-xl text-center text-gray-700"><%= user.rounds.size %></h5>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_who_to_follow.html.erb
<div class="flex flex-col items-start justify-between h-auto mb-6 overflow-hidden bg-white rounded shadow">
    <div class="flex flex-row items-baseline justify-around w-full p-4 pb-0 mb-3">
        <h4>Golfare att följa</h4>
        <div class="flex flex-row">
            <a href="#" class="text-xs text-blue-700 ">Se alla</a>
        </div>
    </div>
    <div class="w-full p-4 pt-0 text-gray-800 bg-gray-100 divide-y divide-gray-400">
        <div class="flex flex-row items-center justify-between py-4">
            <img src="https://uifaces.co/our-content/donated/BMGfa1yq.png" alt="user-1"
                class="w-12 h-12 rounded-full">
            <div class="text-sm">
                <span class="block font-semibold">Deltondo Matthew</span>
                <span class="block text-xs font-light text-gray-700">8 mutual friends</span>
            </div>
            <a href="#"
                class="self-start block px-2 py-px mt-1 text-xs font-semibold tracking-wide uppercase border border-gray-400 rounded-full hover:bg-blue-500 hover:text-white hover:border-transparent">follow</a>
        </div>
        <div class="flex flex-row items-center justify-between py-4">
            <img src="https://uifaces.co/our-content/donated/AVQ0V28X.jpg" alt="user-1"
                class="w-12 h-12 rounded-full">
            <div class="text-sm">
                <span class="block font-semibold">Adriana Cardoson</span>
                <span class="block text-xs font-light text-gray-700">6 mutual friends</span>
            </div>
            <a href="#"
                class="self-start block px-2 py-px mt-1 text-xs font-semibold tracking-wide uppercase border border-gray-400 rounded-full hover:bg-blue-500 hover:text-white hover:border-transparent">follow</a>
        </div>
        <div class="flex flex-row items-center justify-between pt-4">
            <img src="https://uifaces.co/our-content/donated/UZ0VIIh3.png" alt="user-1"
                class="w-12 h-12 rounded-full">
            <div class="text-sm">
                <span class="block font-semibold">Daniela Moreauno</span>
                <span class="block text-xs font-light text-gray-700">2 mutual friends</span>
            </div>
            <a href="#" class="self-start block px-2 py-px mt-1 text-xs font-semibold tracking-wide uppercase border border-gray-400 rounded-full hover:bg-blue-500 hover:text-white hover:border-transparent">follow</a>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<%= render partial: 'articles' %>
<div class="pt-6">
  <div class="grid grid-cols-12 gap-6">
    <div class="hidden col-span-4 md:block xl:col-span-3">
      <div class="sticky top-10">
        <%= render partial: 'user_sidebar', locals: { user: @user } %>
        <%= render partial: 'popular_tags', locals: { tags: @popular_tags } %>
      </div>
    </div>
    <div class="col-span-12 md:col-span-8 xl:col-span-6">
      <%= render partial: 'posts' %>
    </div>
    <div class="hidden xl:block xl:col-span-3">
      <%#= render partial: 'who_to_follow' %>
      <%= render partial: 'leaderboard', locals: { users: @leaderboard_users } %>
      <%= render partial: 'polls' %>
      <!-- <div class="mt-6"><a href="https://www.parmagazine.se">
        <%= image_tag "160267295_428267185132600_181985594661277728_n.gif" %>
      </a> </div>-->
    </div>
  </div>
</div>